version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: utcfcb_redis
    ports:
      - "6380:6379"
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: utcfcb
    restart: always
    ports:
      - "8250:8250"
    env_file:
      - ./.env
    depends_on:
      - redis
    command: python -m src.app